import SwiftUI

/// Preview of the ZacVPN app icon design.
/// The actual icon images are generated by generate_icons.swift (run from terminal).
/// tvOS icon sizes: 400x240 (small), 800x480 (large), 1280x768 (App Store)
struct AppIconView: View {
    var body: some View {
        ZStack {
            // Dark green gradient background (Back layer)
            LinearGradient(
                colors: [
                    Color(red: 0.02, green: 0.14, blue: 0.07),
                    Color(red: 0.06, green: 0.30, blue: 0.15),
                    Color(red: 0.02, green: 0.14, blue: 0.07)
                ],
                startPoint: .topLeading,
                endPoint: .bottomTrailing
            )

            VStack(spacing: 4) {
                // Z-Lock logo (Middle layer)
                Image(systemName: "lock.fill")
                    .font(.system(size: 160, weight: .medium))
                    .foregroundStyle(.white.opacity(0.95))
                    .overlay(
                        Text("Z")
                            .font(.system(size: 80, weight: .heavy, design: .default))
                            .foregroundStyle(Color(red: 0.03, green: 0.22, blue: 0.11))
                            .offset(y: 14)
                    )

                // App name (Front layer)
                Text("ZacVPN")
                    .font(.system(size: 60, weight: .bold))
                    .foregroundStyle(.white.opacity(0.95))
                    .tracking(2)
            }
        }
        .frame(width: 1280, height: 768)
    }
}

#Preview("App Icon - App Store (1280x768)") {
    AppIconView()
}

#Preview("App Icon - Square Crop (768x768)") {
    AppIconView()
        .frame(width: 768, height: 768)
        .clipped()
}
